- name: Install git
  yum:
    name: git
    state: present

- name: Install yum versionlock plugin
  yum:
    name: yum-plugin-versionlock
    state: present

- name: Install dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
    # - virtualenv
    - python-devel
    - libevent-devel
    - gcc
    - gcc-c++
    - kernel-devel
    - libxslt-devel
    - libffi-devel
    - openssl-devel
    - openldap-devel

- name: Versionlock libevent
  command: yum versionlock libevent*

##ToDO: Add https://github.com/cfpb/psql-authnz deployment steps and run on citus hosts and postgres hosts
