# mesos-master
---

### SETUP REPOSITORIES

- name: Add mesosphere repository
  command: "rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm"
  #command: "rpm -Uvh http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm"
  args:
    creates: /etc/yum.repos.d/mesosphere.repo
  when: not 'production' in group_names
  tags:
    - mesos
    - mesos-master

- name: Install the CDH key
  rpm_key:
    key: http://archive.cloudera.com/cdh4/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera
    state: present
  when: not 'production' in group_names
  tags:
    - never
    - mesos
    - mesos-master

- name: Add the CDH repository
  command: "rpm -Uvh http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm"
  args:
    creates: /etc/yum.repos.d/cloudera-cdh4.repo
  when: not 'production' in group_names
  tags:
    - never
    - mesos
    - mesos-master

- name: Add the CDH Repository
  yum_repository:
    name: cloudera-cdh6
    gpgkey: https://archive.cloudera.com/cdh6/6.3.2/redhat7/yum/RPM-GPG-KEY-cloudera
    gpgcheck: yes
    baseurl: https://archive.cloudera.com/cdh6/6.3.2/redhat7/yum/
    description: Cloudera CDH 6 RHEL 7 repo
  tags:
    - never
    - mesos
    - mesos-master

### INSTALL MESOS MASTER PACKAGES

# Note: Even though the installed packages are the same version
# for some reason they must be removed and reinstalled as
# dependencies

# Disable this for now

#- name: Remove incompatible packages
#  yum:
#    name: "{{ item }}"
#    state: absent
#  with_items:
#    - redhat-lsb-graphics
#    - redhat-lsb-core
#  tags:
#    - mesos
#    - mesos-master

- name: Check if /usr/include/mesos/slave is a link
  stat:
    path: /usr/include/mesos/slave
  register: mesos_is_link
  when: mesos_master_fix_link
  tags:
    - mesos
    - mesos-master

- name: Fix the "slave" to "agent" link if needed
  file:
    dest: /usr/include/mesos/slave
    state: absent
  when: mesos_master_fix_link and mesos_is_link.stat.islnk is defined and not mesos_is_link.stat.islnk
  tags:
    - mesos
    - mesos-master

- name: Install yum versionlock plugin
  yum:
    name: yum-plugin-versionlock
    state: present

- name: Install mesos and supporting packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ mesos_server_packages }}"
  notify:
    - restart mesos-master
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Versionlock mesos/marathon packages
  command: yum versionlock mesos* marathon

- name: Clean up RPM generated files in the config directory
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /etc/mesos/*.rpmnew
    - /etc/mesos-master/*.rpmnew
    - /etc/marathon/conf/*.rpmnew
  tags:
    - mesos
    - mesos-master
    - marathon

### CONFIGURE ZOOKEEPER

- name: Configure zookeeper with the IP's of all masters
  template:
    src: zk.j2
    dest: /etc/mesos/zk
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Create zookeeper config folders
  file:
    dest: "{{ item }}"
    state: directory
    owner: root #zookeeper
    group: root #zookeeper
  with_items:
    - "/etc/zookeeper"
  tags:
    - mesos
    - mesos-master

- name: Create zookeeper config file
  template:
    dest: /etc/zookeeper/conf/zoo.cfg
    src: zoo.cfg
    owner: root #zookeeper
    group: root #zookeeper
  tags:
    - mesos
    - mesos-master

- name: Configure number of log files to keep
  lineinfile:
    dest: /etc/zookeeper/conf/log4j.properties
    regexp: "(.*)zookeeper.log.maxbackupindex=(.*)"
    line: "zookeeper.log.maxbackupindex={{ zookeeper_maxbackupindex }}"
  tags:
    - mesos
    - mesos-master

- name: Initialize zookeeper [manual]
  copy:
    dest: /var/lib/zookeeper/myid
    content: "{{ zookeeper_id }}"

- name: Initialize zookeeper
  command: "zookeeper-server-initialize --myid {{ zookeeper_id }}"
  args:
    creates: /var/lib/zookeeper/myid
  tags:
    - never
    - mesos
    - mesos-master

- name: Ensure ownership is correct
  file:
    dest: /var/lib/zookeeper
    state: directory
    recurse: yes
    owner: root #zookeeper
    group: root #zookeeper
  tags:
    - mesos
    - mesos-master

### CONFIGURE MESOS

- name: Set cluster name
  copy:
    dest: /etc/mesos-master/cluster
    content: "{{ mesos_cluster_name }}"
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Configure mesos with the IP's of all zookeepers
  template:
    src: zk.j2
    dest: /etc/mesos/zk
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Update the quorum config file
  template:
    dest: /etc/mesos-master/quorum
    src: quorum.j2
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Add the ip address to the mesos-master folder
  copy:
    dest: /etc/mesos-master/ip
    content: "{{ mesos_master_listen_ip }}"
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Add the ip to the hostname file too
  copy:
    dest: /etc/mesos-master/hostname
    content: "{{ aurora_hostname }}"
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Configure port for Mesos to run on
  lineinfile:
    dest: /etc/default/mesos-master
    line: "PORT={{ mesos_master_port }}"
    regexp: ^(.*)PORT=[0-9]+$
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Configure logging level
  copy:
    dest: /etc/mesos-master/logging_level
    content: "{{ mesos_master_logging_level }}"
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Setup credentials
  template:
    src: mesos_credentials.j2
    dest: /etc/mesos_credentials
    mode: 600
  when: mesos_credentials is defined
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Configure credentials
  copy:
    content: "/etc/mesos_credentials"
    dest: /etc/mesos-master/credentials
  when: mesos_credentials is defined
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Enable framework authentication, if desired
  copy:
    content: "{{ mesos_authenticate_frameworks }}"
    dest: /etc/mesos-master/authenticate
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Enable agent authentication, if desired
  copy:
    content: "{{ mesos_authenticate_agents }}"
    dest: /etc/mesos-master/authenticate_slaves
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

- name: Setup ACL's, if desired
  copy:
    content: "{{ mesos_acls }}"
    dest: /etc/mesos-master/acls
  notify:
    - restart mesos-master
  tags:
    - mesos
    - mesos-master

### CONFIGURE MARATHON

- name: Create Marathon config folders
  file:
    path: /etc/marathon/conf
    state: directory
    mode: 0644
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Copy hostname file to Marathon config
  copy:
    dest: /etc/marathon/conf/hostname
    content: "{{ aurora_hostname }}"
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Copy the zk file to Marathon
  template:
    src: zk.j2
    dest: /etc/marathon/conf/master
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Setup Zookeeper config for Marathon
  template:
    dest: /etc/marathon/conf/zk
    src: zk.marathon.j2
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Confgiure Marathon HTTP port
  copy:
    dest: /etc/marathon/conf/http_port
    content: "{{ marathon_http_port }}"
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Configure Mesos user for Marathon
  copy:
    dest: /etc/marathon/conf/mesos_user
    content: "{{ marathon_mesos_user }}"
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Configure Marathon principal
  copy:
    dest: /etc/marathon/conf/mesos_authentication_principal
    content: "{{ marathon_mesos_principal }}"
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Configure Mesos Framework Authentication
  copy:
    dest: /etc/marathon/conf/?mesos_authentication
    content: ""
  when: mesos_authenticate_frameworks
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Disable Mesos Framework Authentication
  file:
    dest: /etc/marathon/conf/?mesos_authentication
    state: absent
  when: not mesos_authenticate_frameworks
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Configure Marathon secret file path
  copy:
    dest: /etc/marathon/conf/mesos_authentication_secret_file
    content: "{{ marathon_secret_file }}"
    mode: 0600
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Configure Marathon secret
  copy:
    dest: "{{ marathon_secret_file }}"
    content: "{{ marathon_mesos_secret }}"
    mode: 0600
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Configure Marathon artifact store
  copy:
    dest: "/etc/marathon/conf/artifact_store"
    content: "{{ marathon_artifact_store }}"
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Ensure artifact store directory exists
  file:
    dest: "{{ marathon_artifact_store[7:] }}"
    state: directory
    mode: 0755
  when: marathon_artifact_store[:7] == "file://"
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Set Mesos role
  copy:
    content: "{{ marathon_role }}"
    dest: /etc/marathon/conf/mesos_role
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: WebUI URL
  copy:
    content: "{{ marathon_webui_url }}"
    dest: /etc/marathon/conf/webui_url
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Set Marathon Scheduler port number
  template:
    src: marathon.j2
    dest: /etc/default/marathon
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

- name: Set task failure expunge timeout
  copy:
    content: "{{ marathon_task_expunge_timeout }}"
    dest: /etc/marathon/conf/task_lost_expunge_gc
  notify:
    - restart marathon
  tags:
    - mesos
    - mesos-master
    - marathon

### DISABLE MESOS AGENT (INSTALLED BY RPM)

- name: Stop the Mesos agent process
  systemd:
    name: mesos-slave
    state: stopped
    enabled: False
  tags:
    - mesos
    - mesos-master

### START ZOOKEEPER, MESOS, AND MARATHON

- name: Start zookeeper
  systemd:
    name: zookeeper #zookeeper-server
    state: started
    enabled: yes
  tags:
    - mesos
    - mesos-master

- name: Start the Mesos master and Marathon processes (they are already enabled)
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - mesos-master
    - marathon
  tags:
    - mesos
    - mesos-master

- name: Start the Mesos master and Marathon processes (they are already enabled)
  command: "start {{ item }}"
  with_items:
    - mesos-master
    - marathon
  register: mesos_master_start
  failed_when: mesos_master_start.rc != 0 and 'Job is already running' not in mesos_master_start.stderr
  changed_when: mesos_master_start.rc != 0 and 'Job is already running' not in mesos_master_start.stderr
  tags:
    - never
    - mesos
    - mesos-master

## CONFIGURE IP TABLES

# TODO: More restrictive iptables rules are needed, specifically ports
# 5050 and 8080 should only be open to the proxy server, with 5050 also
# open to the Mesos client nodes.  Ports 2181, 2888, and 3888 should be open
# to the Mesos cluster only.
- name: Open required ports
  command: "iptables -I {{ iptables_chain }} 2 -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 2181
    - "{{ mesos_master_port }}"
    - "{{ marathon_http_port }}"
    - "{{ marathon_scheduler_port }}"
    - 2888
    - 3888
  when: iptables_config
  tags:
    - mesos
    - mesos-master

- name: Save iptables
  command: "/sbin/service iptables save"
  when: iptables_config
  notify:
    - restart iptables
  tags:
    - mesos
    - mesos-master

- name: Set recursive admin permissions on log folders
  acl:
    path: "{{ item }}"
    entity: "{{ restricted_group_name }}"
    etype: group
    permissions: rX
    recursive: yes
    state: present
  with_items: "{{ mesos_master_log_file_locations }}"

- name: Set default admin permissions on log folders
  acl:
    path: "{{ item }}"
    entity: "{{ restricted_group_name }}"
    etype: group
    permissions: rX
    default: yes
    state: present
  with_items: "{{ mesos_master_log_file_locations }}"
