# deploy_mesos_master.yml
---
- hosts: mesos_master
  become: yes
  become_method: sudo
  tasks:
    - name: Shutdown all but one of the Mesos Master instances
      service:
        name: mesos-master
        state: stopped
      when: mesos_upgrade and 'mesos_master' in groups and inventory_hostname != groups['mesos_master'][0]

    - name: Shutdown all but one of the Marathon instances
      service:
        name: marathon
        state: stopped
      when: marathon_upgrade and 'mesos_master' in groups and inventory_hostname != groups['mesos_master'][0]

- hosts: mesos_master
  become: yes
  become_method: sudo
  serial: 1
  max_fail_percentage: 30
  roles:
    - {role: iptables, when: "iptables_config"}
    - { role: epel7, when: "use_epel and not ( 'production' in group_names or 'developement' in group_names)" } # This is for rhel7 pip
    - common
    - mesos_master
  tasks:
      # used to install kazoo
    - name: Install pip
      yum:
         name:
            - python2-pip
            - python-setuptools
         state: present

    - name: Install Kazoo (required by Znode ansible module)
      pip:
        name: kazoo
        version: "2.6.1"
        umask: "0022"
      become: yes
